/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type productsquery = {
    products: ({
        id: string;
        name: string;
    })[];
};
export type productsqueryVariables = {};
