/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type ProductReviewFragment = {
    reviews: ({
        id: string;
        commentBody: string;
    })[];
};
export type ProductQuery = {
    product: ({
        id: string;
        name: string;
        description: string;
    } & ProductReviewFragment) | null;
};
export type ProductQueryVariables = {
    pid: string;
};
